spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.197.128:9300
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.222:3306/hxpredp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.owner.es.entity

#showSql
#logging:
#  level:
#    com:
#      example:

